services:
  infotransform:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: infotransform
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - PORT=${PORT:-3000}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - QUIET_MODE=${QUIET_MODE:-false}
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - ./config:/app/config
      - ./frontend:/app/frontend
      - ./app.py:/app/app.py
      - ./data/uploads:/app/data/uploads
      - ./data/temp_extracts:/app/data/temp_extracts
      - ./logs:/app/logs
      - /app/frontend/node_modules
      - /app/frontend/.next
    restart: unless-stopped
    networks:
      - infotransform-network
    stdin_open: true
    tty: true

networks:
  infotransform-network:
    driver: bridge
