version: '3.8'

services:
  infotransform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infotransform
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - PORT=${PORT:-8000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - QUIET_MODE=${QUIET_MODE:-false}
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/temp_extracts:/app/data/temp_extracts
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - infotransform-network

networks:
  infotransform-network:
    driver: bridge

volumes:
  uploads:
  temp_extracts:
  logs:
